{
 "title": "Rclone Metrics",
 "description": "Dashboard for Rclone rc metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Rclone",
    "query": "SHOW TAG VALUES FROM \"rclone_bytes_transferred_total\" WITH KEY=\"url\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rclone_errors_total{service=\"rclone\"}[$__range])"
    }
   ]
  },
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "instance" },
  {
   "title": "Rclone running since",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "process_start_time_seconds",
     "query": "SELECT last(\"gauge\") FROM \"process_start_time_seconds\" WHERE (\"url\" =~ /^$instance$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "process_open_fds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Status Totals",
   "type": "piechart",
   "description": "Since rclone process started",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Checked files",
     "expr": "rclone_checked_files_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checked files",
     "measurement": "rclone_checked_files_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Transferred files",
     "expr": "rclone_files_transferred_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transferred files",
     "measurement": "rclone_files_transferred_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Renamed files",
     "expr": "rclone_files_renamed_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Renamed files",
     "measurement": "rclone_files_renamed_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Deleted files",
     "expr": "rclone_files_deleted_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted files",
     "measurement": "rclone_files_deleted_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Deleted directories",
     "expr": "rclone_dirs_deleted_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted directories",
     "measurement": "rclone_dirs_deleted_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Transfer errors",
     "expr": "rclone_errors_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transfer errors",
     "measurement": "rclone_errors_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Open file descriptors",
     "expr": "process_open_fds{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Open FDs in container {{container}}",
     "measurement": "process_open_fds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Max open file descriptors",
     "expr": "process_max_fds{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "process_max_fds",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "/metrics - Requests by response code",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_code",
     "expr": "promhttp_metric_handler_requests_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "code" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{code}}",
     "measurement": "promhttp_metric_handler_requests_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Transferred in the time range",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(rclone_bytes_transferred_total[$__range])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "rclone_bytes_transferred_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Speed",
   "type": "stat",
   "description": "Since rclone process started",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rclone_speed)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "__auto",
     "measurement": "rclone_speed",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Status per action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Checked files",
     "expr": "rclone_checked_files_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Checked files",
     "measurement": "rclone_checked_files_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Transferred files",
     "expr": "rclone_files_transferred_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transferred files",
     "measurement": "rclone_files_transferred_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Renamed files",
     "expr": "rclone_files_renamed_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Renamed files",
     "measurement": "rclone_files_renamed_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Deleted files",
     "expr": "rclone_files_deleted_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted files",
     "measurement": "rclone_files_deleted_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Deleted directories",
     "expr": "rclone_dirs_deleted_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deleted directories",
     "measurement": "rclone_dirs_deleted_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Transfer errors",
     "expr": "rclone_errors_total{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Transfer errors",
     "measurement": "rclone_errors_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Data transferred",
     "expr": "rclone_bytes_transferred_total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Data transferred",
     "measurement": "rclone_bytes_transferred_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Data Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "Data transfer rate",
     "expr": "rate(rclone_bytes_transferred_total[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Data transfer rate",
     "measurement": "rclone_bytes_transferred_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       },
       { "params": [ "/8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Go threads",
     "expr": "go_threads{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Go threads",
     "measurement": "go_threads",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "CPU seconds",
     "expr": "rate(process_cpu_seconds_total{service=\"rclone\"}[1m])",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "CPU seconds",
     "measurement": "process_cpu_seconds_total",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Allocated bytes",
     "expr": "go_memstats_alloc_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated bytes",
     "measurement": "go_memstats_alloc_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "targets": [
    {
     "alias": "Coroutines",
     "expr": "go_goroutines{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Coroutines",
     "measurement": "go_goroutines",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Heap Objects",
   "type": "timeseries",
   "description": "Total number of allocated objects",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Objects",
     "expr": "go_memstats_heap_objects{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Objects",
     "measurement": "go_memstats_heap_objects",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Go Heap Memory Overview",
   "type": "timeseries",
   "description": "**Allocated:** The amount of memory Rclone is actually using.  \n**Sys:** The amount of memory obtained from the OS.  \n**Sys requested:** The amount of memory requested from the OS.",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Allocated bytes",
     "expr": "go_memstats_sys_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Sys requested bytes",
     "measurement": "go_memstats_heap_alloc_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Sys bytes",
     "expr": "go_memstats_heap_alloc_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated bytes",
     "measurement": "go_memstats_heap_sys_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Idle bytes",
     "expr": "go_memstats_heap_sys_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Sys bytes",
     "measurement": "go_memstats_heap_idle_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "In use bytes",
     "expr": "go_memstats_heap_idle_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Idle bytes",
     "measurement": "go_memstats_heap_inuse_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Released bytes",
     "expr": "go_memstats_heap_inuse_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "In use bytes",
     "measurement": "go_memstats_heap_released_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    },
    {
     "alias": "Sys requested bytes",
     "expr": "go_memstats_heap_released_bytes{service=\"rclone\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Released bytes",
     "measurement": "go_memstats_sys_bytes",
     "select": [
      [
       { "params": [ "gauge" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  }
 ]
}